config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'finder#index'

  get '/customers/missing_email' => 'finder#missing_email', as: 'missing_email'

  get '/customers/alphabetized' => 'finder#alphabetized', as: 'alphabetized'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province
  validates :fullName, presence:true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers_by_order = Customer.all.order(:fullName)
  end

  def missing_email
    @customers_missing_email = Customer.where("email == ''")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.erb
<div id="customer">
  <h2><%= customer.fullName %></h2>
  <%= image_tag"#{customer.image}" %>
  <h4>Phone: <%= customer.phone %></h4>
  <h4>Email: <%= customer.email %></h4>
  <% if(customer.province_id.to_s.empty?) %>
    <h4>Province: None</h4>
  <% else %>
    <h4>Province: <%= customer.province.name %></h4>
  <% end %>
  <h4>Notes: <%= customer.notes %></h4>
</div>

app/views/finder/alphabetized.html.erb
<h1>All Customers By Order<h1>
<h3>
  <%= link_to 'All customers', root_path %>
  -
  <%= link_to 'Customers missing email', missing_email_path %>
</h3>
<%= render partial: 'customers/customer', collection: @customers_by_order %>

app/views/finder/index.html.erb
<h1>All Customers<h1>
<h3>
  <%= link_to 'Customers by order', alphabetized_path %>
  -
  <%= link_to 'Customers missing email', missing_email_path %>
</h3>
<%= render partial: 'customers/customer', collection: @customers %>

app/views/finder/missing_email.html.erb
<h1>All Customers Missing Email<h1>
<h3>
  <%= link_to 'All customers', root_path %>
  -
  <%= link_to 'Customers by order', alphabetized_path %>
</h3>
<%= render partial: 'customers/customer', collection: @customers_missing_email %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrmChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>